---
output: html_document
pagetitle: Meteorite Final Project
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is where my final analysis will be!

So far I have been working the most on making my shiny app, which will be [here](https://bailey-jj.shinyapps.io/Meteor_Map_App/){.uri}.

```{r libraries, include = FALSE}
library(tidyverse)
library(shiny)
library(leaflet)
library(easystats)
library(patchwork)
library(janitor)
library(shinydashboard)
library(data.table)
```

```{r cleaning code, echo=TRUE, message=FALSE, warning=FALSE, collapse=TRUE}
options(scipen = 999)

meteors <- read_csv("./meteorites.csv")

bolides <- read_csv("./bolides.csv")

# In the dataset, there is a correction needed to be made, Northwest Africa 7701, should say 2010, not 2101

meteors[meteors$name == "Northwest Africa 7701", 7] <- 2010
meteors[meteors$name == "Northwest Africa 7701", 7]

### Meteor Cleaning and Mapping ####
m_circles <- 
  meteors %>% 
  filter(!is.na(meteors$lat) & !is.na(meteors$long))

### Bolides Cleaning and Mapping (May or may not use this dataset in the end product) ####
b_circles <-  
  bolides %>% 
  janitor::clean_names() %>% 
  filter(!is.na(bolides$latitude) & !is.na(bolides$longitude)) %>% 
  filter(!is.na(bolides$`altitude(km)`) & !is.na(bolides$`total impact energy`))

b_circles <- 
  b_circles %>%
  separate(col = latitude, into = c('lat', 'direction'), sep = -1, remove = FALSE) %>%
  mutate(long = as.numeric(lat)) %>% 
  select(-latitude) %>% 
  separate(col = longitude, into = c('long', 'direction2'), sep = -1, remove = FALSE) %>%
  mutate(long = as.numeric(long)) %>% 
  select(-longitude)

b_circles <- 
  within(b_circles, {
    lat <- ifelse(direction=="N", lat, (as.numeric(lat) * -1))
  }) %>% 
  select(-direction)

b_circles <- 
  within(b_circles, {
    long <- ifelse(direction2=="E", long, (as.numeric(long) * -1))
  }) %>% 
  select(-direction2)

b_circles$lat <- b_circles$lat %>% as.numeric
b_circles$long <- b_circles$long %>% as.numeric
```

```{r exploring, message=FALSE, warning=FALSE, collapse=TRUE}
### Exploring data ####

m_circles %>% 
  filter(!is.na(year)) %>% 
  ggplot(aes(x = year, y = mass, color = name_type)) + 
  geom_point()

# This graph shows the expected results, that there are more meteors being found from 1700s to current day.

max(m_circles$year, na.rm = TRUE)
min(m_circles$year, na.rm = TRUE)

max(m_circles$mass, na.rm = TRUE)
min(m_circles$mass, na.rm = TRUE)

place_names <- 
  m_circles %>% 
  filter(!is.na(year)) %>% 
  mutate(name = trimws(str_remove(name, "(\\s+[A-Za-z]+)?[0-9-]+")))

unique(place_names$name)
```
